version: "3.9"
services:
  mssql:
      image: 'mcr.microsoft.com/mssql/server'
      ports:
          - '1400:1433'
      environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=Dariaman46
      volumes:
        - '/mnt/d/db:/var/opt/mssql/data'